### ISSUE TITLE
latest charts and not being published in helm hub?

### ISSUE THREAD

**Issue by subashd** [helm/hub#165] opened 2019-10-11 12:39 UTC
i have pushed latest charts with version 1.1.0 of 
citrix/citrix-adc-istio-ingress-gateway
and 
citrix/citrix-cpx-istio-sidecar-injector

but still here in helm hub it is showing old charts??

reference:
https://github.com/citrix/citrix-istio-adaptor/tree/gh-pages
 https://citrix.github.io/citrix-istio-adaptor/

**Comment by munnerz** [comment] 2019-10-15 08:17
:+1: I am seeing the same with our cert-manager repository. Please see #2202 for more details. Who is best to escalate this too? I'm unsure which org/individual runs/administrates the Helm Hub.

**Comment by JulienBreux** [comment] 2019-10-15 08:21
Hello @prydonius same bug as https://github.com/helm/hub/issues/134 ?

Thanks

**Comment by rimusz** [comment] 2019-10-15 08:29
@mattfarina are we still facing https://github.com/kubernetes/kubernetes/issues/77465 issue?

**Comment by mattfarina** [comment] 2019-10-15 20:48
The issue is the one @rimusz noted. Updates are a little slow because we have to clear out jobs, etc to get it going again. I've emailed folks to see about getting a version of k8s in the public cloud we're using with the fixed version of k8s as a stable version.

At the moment neither Azure or GKE have a stable version of Kubernetes at version 1.14 or newer with the bug fixed.

We are aware of this and working on it.

**Comment by JulienBreux** [comment] 2019-10-16 07:38
@mattfarina thanks.

Could you notify us here when it's ok? 🙏

**Comment by mattfarina** [comment] 2019-10-16 13:58
@JulienBreux I will close this issue when it's fixed. Until then you will likely see updates once a day and possibly have one skipped on a weekend.

**Comment by JulienBreux** [comment] 2019-10-16 15:37
@mattfarina enjoy! It's ok!

/close

**Comment by subashd** [comment] 2019-10-16 15:53
@mattfarina thank you ... charts are upadted :)

**Closed** 2019-10-16 15:52 UTC
