### ISSUE TITLE
Grafana Chart now showing

### ISSUE THREAD

**Issue by phumberdroz** [helm/hub#223] opened 2020-01-05 14:34 UTC
I am not sure if this is an Issue for this Repo or is better to be posted to monocular

https://hub.helm.sh/charts?q=grafana

Does not show the `stable/grafana` chart and I am unsure what could be causing this since it is reachable here: https://hub.helm.sh/charts/stable/grafana

**Comment by scottrigby** [comment] 2020-01-14 23:38
I believe this is a duplicate of https://github.com/helm/hub/issues/187. This is an issue with the whitespace… scroll down and you should see the chart.

**Closed** 2020-01-14 23:41 UTC

**Comment by phumberdroz** [comment] 2020-01-15 13:40
oh 👍
