### ISSUE TITLE
Search on hub.helm.sh does not filter search results as expected

### ISSUE THREAD

**Issue by jcantosz** [helm/hub#232] opened 2020-01-14 18:37 UTC
Issue is 2 fold:
1. Searching in all does not seem to aggregate from *all* categories.
2. Switching category from `all` to `stable` does not seem to update the search result

I would expect all to show results aggregated from all categories and would expect switching categories on an active search would update the results,

To reproduce:
1. Search for the chart `jenkins` from [https://hub.helm.sh/charts/](https://hub.helm.sh/charts/)
2. Click on the `stable` link. Notice that the url changes to [https://hub.helm.sh/charts/stable](https://hub.helm.sh/charts/stable), but the results do not change
3. Select the search box and press enter. Notice that the url does not change but the results do.

In addition, the chart listed under `stable` is not present under `all`. 

There are no errors in the console if I got to inspect.

Step 1
<img width="695" alt="Screen Shot 2020-01-14 at 1 35 27 PM" src="https://user-images.githubusercontent.com/22500761/72371636-cab34600-36d2-11ea-9b6a-734c64dbcbff.png">

Step 2
<img width="747" alt="Screen Shot 2020-01-14 at 1 21 40 PM" src="https://user-images.githubusercontent.com/22500761/72371543-99d31100-36d2-11ea-8350-a9aed8859f8d.png">

Step 3
<img width="535" alt="Screen Shot 2020-01-14 at 1 22 12 PM" src="https://user-images.githubusercontent.com/22500761/72371528-92ac0300-36d2-11ea-97ef-50540f723857.png">

**Comment by scottrigby** [comment] 2020-01-14 23:40
I believe this is a duplicate of #187. This is an issue with the whitespace… scroll down and you should see the chart.

**Closed** 2020-01-14 23:40 UTC

**Comment by jcantosz** [comment] 2020-01-15 00:29
You are correct. Thank you!
